### ISSUE TITLE
Data set validation

### ISSUE THREAD

**Issue by asuender** [asuender/sotodo#11]
Yeah, that's it. `sotodo` can check custom user data sets in `directory` by parsing the following arguments:

```console
foo@user:~/path/to/user/data$ sotodo -c directory
```

**Comment by ProgrammeYourself** [comment]
See commit [7213e122d5b71818ba4aaebd7fa8e81a5699b27c](https://github.com/ProgrammeYourself/sotodo/commit/7213e122d5b71818ba4aaebd7fa8e81a5699b27c#diff-5bc02cefb3ea9e27f1a6776eabd1935d)

**Comment by ProgrammeYourself** [comment]
Waiting for @RiedleroD to fix my code. Yeet.

**Comment by RiedleroD** [comment]
forgot to close issue, whoops
